[project]
name = "tasky-settings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Alexis Beaulieu", email = "alexisbeaulieu97@gmail.com" }]
requires-python = ">=3.13"
dependencies = ["pydantic-settings>=2.11.0"]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"
