exclude = [".venv"]

line-length = 100
indent-width = 4
target-version = "py314"

[format]
indent-style = "space"
quote-style = "double"
line-ending = "lf"

docstring-code-format = true

[lint]
select = ["E4", "E7", "E9", "F", "C901"]
ignore = []

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.mccabe]
max-complexity = 5