exclude = [".venv"]

line-length = 100
indent-width = 4
target-version = "py314"

[format]
indent-style = "space"
quote-style = "double"
line-ending = "lf"

docstring-code-format = true

[lint]
select = ["ALL"]
ignore = ["D203", "D107", "D213", "TC002", "TC003"]

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"**/tests/**/*.py" = [
    "S101",
    "PLR2004",
    "INP001",
] # Allow assert statements, magic values, and implicit namespace packages in tests

[lint.mccabe]
max-complexity = 5
