[project]
name = "tasky-tasks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alexis Beaulieu", email = "alexisbeaulieu@protonmail.com" },
]
requires-python = ">=3.13"
dependencies = ["pydantic>=2.12.3", "tasky-logging", "tasky-hooks"]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
tasky-logging = { workspace = true }
tasky-hooks = { workspace = true }
