[project]
name = "tasky-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alexis Beaulieu", email = "alexisbeaulieu97@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "tasky-models",
    "tasky-storage",
    "tasky-shared",
]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
tasky-models = { workspace = true }
tasky-storage = { workspace = true }
tasky-shared = { workspace = true }

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
