[project]
name = "tasky-shared"
version = "0.1.0"
description = "Shared utilities for Tasky packages"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"
