[project]
name = "tasky-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alexis Beaulieu", email = "alexisbeaulieu97@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "typer>=0.20.0",
    "rich>=13.8.0",
    "tasky-core",
    "tasky-settings",
]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
tasky-core = { workspace = true }
tasky-settings = { workspace = true }
